name: Daily Claim Rewards - QQ Music

on:
  schedule:
    # Run every day at midnight UTC
    - cron: "0 0 * * *"  # The schedule here is UTC, adjust to your desired time if necessary
  workflow_dispatch:  # Allows manual trigger from the GitHub UI

jobs:
  refresh-cookie:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      
      - name: Install Python dependencies
        run: |
          pip install requests


      - name: Restore cookie
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: .cookie
          key: cookie-cache-${{ runner.os }}
          restore-keys: |
            cookie-cache-${{ runner.os }}

      - name: Read musickey from cookie
        id: read_cookie
        run: |
          if [ -f .cookie ] && [ -s .cookie ]; then
            echo "Using cached cookie:"
            cat .cookie
            echo "musickey=$(cat .cookie)" >> $GITHUB_OUTPUT
          else
            echo "Cache miss or empty .cookie, using fallback secret"
            echo "${{ secrets.MUSIC_KEY }}" > .cookie
            echo "musickey=${{ secrets.MUSIC_KEY }}" >> $GITHUB_OUTPUT
          fi

      - name: Get signature
        id: sign_step
        run: |
          set +x
          echo "::add-mask::${{ steps.read_cookie.outputs.musickey }}"
          echo "::add-mask::${{ secrets.QQ }}"
          
          node qq_music/sign.js
        env:
          GITHUB_OUTPUT: $GITHUB_OUTPUT
          MUSIC_KEY: ${{ steps.read_cookie.outputs.musickey }}
          MUSIC_ID: ${{ secrets.QQ }}


      - name: Run Python script to refresh cookie
        run: |
          echo "::add-mask::${{ steps.read_cookie.outputs.musickey }}"
          echo "::add-mask::${{ secrets.QQ }}"
          echo "::add-mask::${{ steps.sign_step.outputs.sign }}"

          python -m qq_music.refresh_cookie --key="${{ steps.read_cookie.outputs.musickey }}" --uin="${{ secrets.QQ }}" --sign="${{ steps.sign_step.outputs.sign }}"
        env:
          BARK_DEVICE_KEY: ${{ secrets.BARK_DEVICE_KEY }}
          UIN: ${{ secrets.QQ }}
          SIGN: ${{ steps.sign_step.outputs.sign }}
          MUSIC_KEY: ${{ steps.read_cookie.outputs.musickey }}

      - name: Save cookie
        uses: actions/cache/save@v4
        with:
          path: .cookie
          key: cookie-cache-${{ runner.os }}-${{ github.run_id }}
